# This file was generated by https://github.com/kamilchm/go2nix v1.2.0
{ stdenv, buildGoPackage, fetchgit, fetchhg, fetchbzr, fetchsvn }:

buildGoPackage rec {
  name = "Siad-${version}";
  version = "2017-05-19";
  rev = "4c624d99e2ea89d3f1e9a40917970ee273a891a0";

  goPackagePath = "github.com/NebulousLabs/Sia";
  subPackages = [ "siad" ];

  src = fetchgit {
    inherit rev;
    url = "https://github.com/NebulousLabs/Sia";
    sha256 = "1lfcv624mgbrp073va8znvcaws0ayib6d7rq0g4r6qpjzjvda8is";
  };

  goDeps = ./deps.nix;

  # TODO: add metadata https://nixos.org/nixpkgs/manual/#sec-standard-meta-attributes
  meta = {
  };
}
