# This file was generated by https://github.com/kamilchm/go2nix v1.2.0
[
  {
    goPackagePath = "github.com/bgentry/speakeasy";
    fetch = {
      type = "git";
      url = "https://github.com/bgentry/speakeasy";
      rev = "4aabc24848ce5fd31929f7d1e4ea74d3709c14cd";
      sha256 = "02dfrj0wyphd3db9zn2mixqxwiz1ivnyc5xc7gkz58l5l27nzp8s";
    };
  }
  {
    goPackagePath = "github.com/inconshreveable/go-update";
    fetch = {
      type = "git";
      url = "https://github.com/inconshreveable/go-update";
      rev = "8152e7eb6ccf8679a64582a66b78519688d156ad";
      sha256 = "07czhspakpi7al004rm669cmf4h5l0vnygsm11280nkfn2zxqdi3";
    };
  }
  {
    goPackagePath = "github.com/julienschmidt/httprouter";
    fetch = {
      type = "git";
      url = "https://github.com/julienschmidt/httprouter";
      rev = "975b5c4c7c21c0e3d2764200bf2aa8e34657ae6e";
      sha256 = "1ka14l3qskknn2ivln5k7gkamqi8h8scgqrv8wc9harp8a7sg4hx";
    };
  }
  {
    goPackagePath = "github.com/kardianos/osext";
    fetch = {
      type = "git";
      url = "https://github.com/kardianos/osext";
      rev = "ae77be60afb1dcacde03767a8c37337fad28ac14";
      sha256 = "056dkgxrqjj5r18bnc3knlpgdz5p3yvp12y4y978hnsfhwaqvbjz";
    };
  }
  {
    goPackagePath = "github.com/spf13/cobra";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/cobra";
      rev = "ca57f0f5dba473a8a58765d16d7e811fb8027add";
      sha256 = "1lycnfkby5c7aamvwgxwq6ivzyvd8r761zkdignww1rmnqmiwd2h";
    };
  }
  {
    goPackagePath = "github.com/spf13/pflag";
    fetch = {
      type = "git";
      url = "https://github.com/spf13/pflag";
      rev = "e57e3eeb33f795204c1ca35f56c44f83227c6e66";
      sha256 = "13mhx4i913jil32j295m3a36jzvq1y64xig0naadiz7q9ja011r2";
    };
  }
]
