# This file is autogenerated from update.sh in the same directory.
{
  beta = {
    sha256 = "1lix5wzcwf666vsdbdzz071rynswlxg5414k3nsrmlxwxhyh6qi4";
    sha256bin64 = "02cv9vc1l2nlwa4a0lc7cj9c9czrwp1jd8d024bq16a5fvmhl01l";
    version = "54.0.2840.50";
  };
  dev = {
    sha256 = "02zlz4b9rpd57hfzw5jpnzdx746cckdmkfqj8wmij8kxfjrl67m9";
    sha256bin64 = "00bg43k00shcabwv9wv1ipy9y0gwrr769rb18gpkj39xrmv3qzh7";
    version = "56.0.2897.0";
  };
  stable = {
    sha256 = "0zfxwygqjhq37agqpn34nvjwa8ijm7xc9l6hwv89m5rs1gmx60nj";
    sha256bin64 = "1mlqxglbqdqnhsmy1p6jn1z9md0lsia6lrhw11q7d523masvbb1m";
    version = "54.0.2840.71";
  };
}
